#!/bin/bash

#Setting the path for sqlite database
DB_PATH="var/obhapp.sqlite3"

# Check if database file exists
if [ ! -f "$DB_PATH" ]; then
  echo "Error: can't find database $DB_PATH"
  echo "Try: ./bin/obhdb create"
  exit 1
fi

# npx webpack --watch &

# Running the development server
echo "+ flask --app obhapp --debug run --host 0.0.0.0 --port 8000"
flask --app obhapp --debug run --host 0.0.0.0 --port 8000